### ISSUE TITLE
기능 별 이슈 정리

### ISSUE THREAD

**Issue by hello2jolee** [hello2jolee/cat-mom#2]

**Comment by sujeong0903** [comment]
### 필요한 기능 

- 메인  
- 회원가입
- QR코드 발급 및 정보 입력(+GPS)
- QR코드 입력(+카메라 촬영모드)
- 정보 페이지(+커뮤니티) 
- 지도 페이지

**Comment by sujeong0903** [comment]
## 기능
### 메인
### 회원가입, 로그인, 사용자 정보 수정
### QR코드 발급 및 정보 입력 
사용자가 해당 로케이션에 대한 정보를 입력
-  로케이션 id 
-  경도, 위도 
-  담당자
-  고양이 수 
-  배식 가능 날짜
### QR코드 입력
그릇에 붙은 QR코드를 입력해 해당 페이지로 이동
### 정보 페이지 
QR코드 입력, 지도 클릭시 노출되는 페이지
-  로케이션 id 
-  경도, 위도 
-  담당자
-  고양이 수 
-  배식 여부
-  댓글, 사진 
### 지도 페이지 
현재 위치를 기준으로 QR코드가 있는 로케이션 표시 (c.c [굿닥](https://www.goodoc.co.kr/hospitals))
Google Map API
-  로케이션 id 
-  경도, 위도 
-  배식 여부
### 신고
수상한 사용자 신고
### 검색
고양이, 위치, 배식 여부를 기준으로 로케이션 검색
